name: NuxtJS Build

on:
  push:
    paths-ignore:
      - "android/**"
      - "ios/**"
      - "capacitor.config.json"
  pull_request:
    paths-ignore:
      - "android/**"
      - "ios/**"
      - "capacitor.config.json"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: nuxtjs-output
          path: .output/public/
